spring.session.store-type: none

# Authenticator --------------------------------------
facebook.token_info.url:

google:
  credential:
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
  token_info.url:

---
spring:
  profiles: local

server:
  port: 8085
---
spring:
  profiles: docker

server:
  port: 8080