server:
  port: 8866

spring:
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/tmp/source/spring-cloud/cloud-config-server/files-config-repo/
